---
functional:
  - Авторизованный пользователь должен иметь возможность принимать участие в игре с ботом
  - Авторизованный пользователь должен иметь возможность принимать участие в игре с другими пользователемя
  - Авторизованный пользователь должен иметь возможность принимать участие в игре с другом
  - Авторизованный пользователь должен иметь возможность изменять уровень сложности
  - Пользователь должен иметь возможность просмотра игры других пользователей
  - Авторизованный пользователь должен иметь возможность писать сообщения в чате
  - Пользователь должен иметь возможность просмотра записи игр
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен иметь мобильную версию.
